  name: shenko
  version: '0.1.83' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Shenko.org is a open source community check us out on youtube
  description: |
    Welcome to shenko, our goal when creating this community is to write software and build hardware using open source tools. We wanted to write the entire project in python as this is a programming language best suited for learning. Blender is a 3d software that allows us to create game assets and upload to the shenko website to share or import into the Panda3d game environment (that also uses python) and build the most epic 3d community.
  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
   shenko:
     plugin: python
     python-version: python2 
     source: .

  apps:
    shenko:
      command: bin/shenko
      desktop: usr/share/applications/shenko.desktop
      plugs:
        - desktop
        - desktop-legacy
        - wayland
        - unity7

